// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfgzbtuytxhmrxirftts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmZ3pidHV5dHhobXJ4aXJmdHRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjU0MzksImV4cCI6MjA2NDgwMTQzOX0.Dc0UMLwnZp65TWlY_4RFT1VyVIg8Zc-X4MFTjV5-2S0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);